export const GET_ALL_POKEMONS='GET_ALL_POKEMONS';
export const GET_DETAIL_POKEMON='GET_DETAIL_POKEMON';
export const GET_TYPES='GET_TYPES';
export const GET_POKEMON_BY_NAME='GET_POKEMON_BY_NAME';

export const ORDER_POKEMONS='ORDER_POKEMONS';
export const FILTER_POKEMONS='FILTER_POKEMONS';
export const FILTER_TYPES='FILTER_TYPES';

export const CLEAN_DETAIL='CLEAN_DETAIL';
export const CLEAN_INFO_FILTERS='CLEAN_INFO_FILTERS';
